media:
  - name: images
    label: Images
    input: src/assets
    output: /src/assets
    extensions: [ png, jpg ]
content:
  - name: posts
    label: Posts
    path: src/content/blog
    type: collection
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - name: pubDate
        label: PubDate
        type: date
        options:
          format: MMM dd yyyy
      - { name: heroImage, label: HeroImage, type: image }
      
  